acc/urls.py
from django.urls import path
from . import views
app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete')
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("detail/<bpk>", views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name='delete'),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>', views.creply, name ='creply'),
    path('dreply/<bpk><rpk>',views.dreply, name ='dreply'),
    path('likey/<bpk>', views.likey, name ="likey"),
    path('unlikey/<bpk>', views.unlikey, name ="unlikey")
   
]

book/urls.py
from django.urls import path
from . import views

app_name ="book"

urlpatterns = [
     path('index/', views.index, name="index"),
     path('create/', views.create, name="create")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('vote/', include('vote.urls')),
    path('trans/', include('trans.urls')),
    path('book/', include('book.urls'))    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from tkinter import CASCADE
from django.db import models
from acc.models import User
# Create your models here.

class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer") # 1:N 관계
    content = models.TextField()
    pubdate = models.DateTimeField()    # 최신 글 가장 위로 
    likey = models.ManyToManyField(User, blank=True, related_name="likey")    # 투표 기능 할때!! N:N 관계

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 70:
            return f"{self.content[:70]}..."
        return self.content

    def hot(self):
        if self.likey.count() >=2:
            return True
        return False

class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete= models.CASCADE)
    replyer = models.ForeignKey(User, on_delete= models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.board}_{self.replyer}"

board/views.py
from django.shortcuts import redirect, render
from .models import Board,Reply
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages
# 페이징 기능 구현====================================================================
def index(req):
    pg = req.GET.get("page", 1)
    b = Board.objects.all()

    cate = req.GET.get("cate","")
    ss = req.GET.get("ss","")  

    if ss:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=ss)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=ss)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none() #아무것도 없는 레코드 설정할때

        elif cate == "con":
            b = Board.objects.filter(content__contains=ss)
        else:
            b = Board.objects.all()
    else:
        b = Board.objects.all()
    
    b = b.order_by('-pubdate')
    
    pag = Paginator(b,5)
    obj = pag.get_page(pg)

    context = {
        "bset" : obj,
        "ss" : ss,
        "cate" : cate,

    }
    return render(req, "board/index.html", context)
#CRUD=================================================================================
 
def detail(req,bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context ={
        "b" : b,
        "rset" : r
    }
    return render(req, "board/detail.html", context)

def delete(req,bpk):
    b = Board.objects.get(id=bpk)
    if b.writer == req.user:
        b.delete()
    else:    # hacking
        messages.error(req, "Invalid connection")
    return redirect("board:index")


def create(req):
    if req.method == "POST":
        s = req.POST.get("sub")
        c = req.POST.get("con")
        Board(subject=s, writer=req.user, content=c, pubdate=timezone.now()).save()
        return redirect("board:index")
    return render(req, "board/create.html")

def update(req,bpk):
    b = Board.objects.get(id=bpk)

    if b.writer != req.user:
        pass
        return redirect("board:index")

    if req.method == "POST":
        s = req.POST.get("sub")
        c = req.POST.get("con")
        b.subject = s
        b.content = c
        b.save()
        return redirect("board:index")
    context ={
        "b":b
    }    
    return render(req, "board/update.html",context)

# 댓글기능 구현=====================================================================
def creply(req,bpk):
    b = Board.objects.get(id=bpk)
    c = req.POST.get('com')
    Reply(board=b,replyer=req.user,comment=c).save()

    return redirect("board:detail",bpk)



def dreply(req,bpk,rpk):
    r = Reply.objects.get(id=rpk)
    if r.replyer == req.user:    
        r.delete()
    else:
        messages.error(req, "Invalid connection")
    return redirect("board:detail",bpk)


def likey(req,bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(req.user)
    
    return redirect("board:detail",bpk)

def unlikey(req,bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(req.user)

    return redirect("board:detail",bpk)

templates/board/create.html
{% extends 'base.html' %}

{% block con %}
 


<div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
    <h1><b>게시글 작성</b></h1>
    
    <form method="post">
        {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name ="sub" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name ="con" style="height: 150px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
    </form>
</div>


{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}

{% block con %}
    <div class ="container mt-5 mb-5">

        
        
        <h1><b>{{b.subject}}</b></h1>
        <hr>
        
        <div class="row mt-5">
            <div class="col-lg-8">
                <textarea class="form-control"  disabled style="height: 250px;">{{b.content}}</textarea>
            </div>
            <div class="col-lg-4">
                <img src="{{b.writer.getpic}}" width="100%">
                <div class ="text-center">
                    <h7>Written by <b>{{b.writer}}</b></h7>
                </div>
                <div class ="text-end mt-2">
                    {{b.pubdate | date:'Y년 n월 j일 H:i' }}
                </div>
            </div>
        </div>
    

        <div class="text-end mt-4">
            <a href="{% url 'board:index' %}"><button class="btn btn-dark">LIST</button></a>
            {% if user == b.writer %}
                <a href="{% url 'board:update' b.id %}"><button class="btn btn-dark">MOD</button></a>         
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    DEL
                </button>
            {% endif %}

            {% if user in b.likey.all %}
                <a class="btn btn-danger" href ="{% url 'board:unlikey' b.id %}">♡</a>
            {% else %}
                <a class="btn btn-primary" href ="{% url 'board:likey' b.id %}">♥</a>
            {% endif %}
            
                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#star">
                    즐겨찾기
                </button>

               

        </div>

        <hr>
        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <div class ="row">
                <div class="col-lg-10">
                    <input typre="text" name="com" class="form-control">
                </div>
                <div class="col-lg-2">                
                    <button class ="btn btn-dark style="width: 100%;">댓글생성</button>                   
                </div>
            </div>
        </form>

        <hr>
        <h2>{{b.site_name}} Comment</h2>
        {% if rset %}
            {% for i in rset %}
                <div class="row mt-5">
                    <div class="col-lg-4">
                        <img src ="{{i.replyer.getpic}}" width="90%">
                        <div class ="text-front">
                            <h5><b>{{i.replyer}}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-8" style="margin: auto;">
                        <textarea class="form-control" style="height: 150;" disabled>{{i.comment}}</textarea>
                        {% if i.replyer == user %}
                        <div class ="text-end mt-4">
                                <a href="{% url 'board:dreply' b.id i.id %}" class ="btn btn-danger">DEL</a>
                        </div>
                        {% endif%}
                    </div>
                </div>
            {% endfor %}
        {% else %}
                <div class="text-center mt-5">
                    <h2>댓글 없음</h2>
                </div>
        {% endif%}
    </div>
    



    <!-- 삭제알림창  -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">DEL</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                <h3>진짜 지울꺼야?.....</h3>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url 'board:delete' b.id %}"><button type="button" class="btn btn-danger">DEL</button></a>
                </div>
            </div>
        </div>
      </div>

     <!-- 즐겨찾기알림창 -->
     <div class="modal fade" id="star" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">즐겨찾기 알림</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <form method="post" action="{% url 'book:create' %}">
                    {% csrf_token %}
                    <div class="modal-body text-center">
                        <div class="text-end">
                            <input type="checkbox" name="impo" class="btn-check" id="btn-check-outlined" autocomplete="off">
                            <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                        </div>
                        <textarea class="form-control mt-3" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                        <input type="hidden" name="sname" value="[게시판]::{{ b.subject }}">
                        <input type="hidden" name="surl" value="{{ request.path }}">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-dark">생성</button>
                    </div>
                </form>

            </div>
        </div>
    </div>





{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% load mathfilters %}

{% block con %}
 
    <div class ="container mt-5 mb-5">
        <h1><b>게시판</b></h1>
    
        <div class="text-end">
            <a href="{% url 'board:create' %}" class="btn btn-dark">Create</a>
        </div>

        <table class="table table-hover mt-5">
            <thead style="background-color:black ; color: white;">
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">SUMMARY</th>
                    <th scope="col">WRITER</th>
                    <th scope="col">Likey</th>
                </tr>
            </thead>
            <tbody>
            {% if bset %}
                {% for i in bset%}
                
                    <tr {% if i.hot %} style="background-color: rgb(219, 67, 21);" {% endif %}>
                        <th scope="row">{{ bset.start_index|add:forloop.counter0}}</th>
                        <td><a href="{% url 'board:detail' i.id %}">{{i.subject}}</a></td>
                        <td>{{i.summary}}</td>
                        <td>{{i.writer}}</td>
                        <td>{{i.likey.count}}</td>
                    </tr>
                {% endfor %}
            {% else %}
            <tr>
                {% if ss %}
                    <th colspan="5" class="text-center">
                        <b>검색결과가 없습니다</b>
                    </th>
                {% else %}
                    <th colspan="5" class="text-center">
                        <b>게시글이 없어여</b>
                    </th>
                {% endif %}
              
            </tr>
            {% endif %}
            </tbody>
          </table>
    
        <nav aria-label="Page navigation example" class="mt-5">
            <ul class="pagination justify-content-center">
                {% if bset.has_previous %}
                    <li class="page-item">                   
                        <a class="page-link" href="{% url 'board:index' %}?page=1&ss={{ss}}&cate={{cate}}">Home</a>
                    </li>
                    <li class="page-item">                   
                        <a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&ss={{ss}}&cate={{cate}}">이전</a>
                    </li>        
                {% else %}                    
                <li class="page-item disabled">
                    <a class="page-link">Home</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link">이전</a>
                </li>                      
                {% endif %}
                

                {% for i in bset.paginator.page_range %}
                    {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
                        <li class="page-item {% if i == bset.number%} active {% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&ss={{ss}}&cate={{cate}}">{{i}}</a></li>
                    {% endif %}
                {% endfor %}
                
                {% if bset.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&ss={{ss}}&cate={{cate}}">다음</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&ss={{ss}}&cate={{cate}}">마지막</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">다음</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">마지막</a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    
        <br><br>
            <form>
                <div class="row mt-4"> 
                    <div class="col-lg-2 text-end">           
                            <select class="form-select mb-3" name ="cate" aria-label=".form-select-lg example">
                                <option value="sub" {% if cate == "sub"%} selected {% endif %}>제목</option>
                                <option value="wri" {% if cate == "wri"%} selected {% endif %}>작성자</option>
                                <option value="con" {% if cate == "con"%} selected {% endif %}>내용</option>
                            </select>                        
                    </div>

                    <div class="col-lg-8 text-end">
                        <input type ="text" name="ss" class="form-control" value="{{ss}}">
                        
                    </div>

                    <div class="col-lg-2 text-end">                    
                        <button class="btn btn-dark">검색</button>
                        <a href="{% url 'board:index' %}" class="btn btn-dark">Main</a>                    
                    </div>
                </div>
            </form>      
    </div>



{% endblock %}

templates/board/update.html
{% extends 'base.html' %}

{% block con %}
 

<div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
    
    <h1><b>게시글수정</b></h1>

        <form method="post">
            {% csrf_token %}  
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="sub" value="{{b.subject}}"class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" disabled value="{{ b.writer }}">
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="con" style="height: 150px;">{{b.content}}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">수정</button>
            </div> 
        </form>  
</div>

{% endblock %}